"""initial schema

Creates all six Sprint 6 tables (users, trades, ai_analyses,
scoring_weights, ml_exports, ml_models) and seeds the single Sprint-6
user row (id=1, local@tradeedge.ai) that every request implicitly acts
as (see app/deps.py and Section 12 of the architecture spec).

Revision ID: 0001_initial
Revises: None
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('ml_exports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('dataset_version', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ml_exports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_exports'))
    )
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_rows', sa.Integer(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ml_models_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_models'))
    )
    op.create_table('scoring_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_weights', sa.JSON(), nullable=True),
    sa.Column('execution_weights', sa.JSON(), nullable=True),
    sa.Column('similarity_weights', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scoring_weights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_weights')),
    sa.UniqueConstraint('user_id', name=op.f('uq_scoring_weights_user_id'))
    )
    op.create_table('trades',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pair', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('asset', sa.String(length=32), nullable=True),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('exit', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('lots', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('rr', sa.Float(), nullable=True),
    sa.Column('h4_trend', sa.String(length=32), nullable=True),
    sa.Column('h4_poi_type', sa.String(length=32), nullable=True),
    sa.Column('premium_discount', sa.String(length=32), nullable=True),
    sa.Column('m15_confirmations', sa.JSON(), nullable=True),
    sa.Column('session', sa.String(length=32), nullable=True),
    sa.Column('news', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('followed_plan', sa.String(length=16), nullable=True),
    sa.Column('rules_followed', sa.String(length=32), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('emotion', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('worked', sa.Text(), nullable=True),
    sa.Column('failed', sa.Text(), nullable=True),
    sa.Column('worked_tags', sa.JSON(), nullable=True),
    sa.Column('failed_tags', sa.JSON(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('rule_score', sa.Integer(), nullable=True),
    sa.Column('execution_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('rule_recommendation', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('buy', 'sell')", name=op.f('ck_trades_direction_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trades_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index('ix_trades_user_date', 'trades', ['user_id', 'date'], unique=False)
    op.create_index('ix_trades_user_pair', 'trades', ['user_id', 'pair'], unique=False)
    op.create_index('ix_trades_user_session', 'trades', ['user_id', 'session'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_score', sa.Integer(), nullable=True),
    sa.Column('execution_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=16), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('rule_breakdown', sa.JSON(), nullable=True),
    sa.Column('execution_breakdown', sa.JSON(), nullable=True),
    sa.Column('passed_reasons', sa.JSON(), nullable=True),
    sa.Column('missing_confirmations', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('mistakes', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('rule_engine_version', sa.String(length=16), nullable=True),
    sa.Column('execution_engine_version', sa.String(length=16), nullable=True),
    sa.Column('weights_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_ai_analyses_trade_id_trades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_index('ix_ai_analyses_trade_created', 'ai_analyses', ['trade_id', 'created_at'], unique=False)
    op.create_index('ix_ai_analyses_user_created', 'ai_analyses', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Seed the single Sprint-6 user. Every router defaults to acting as
    # this user until Sprint 8 auth exists (app/deps.py:DEFAULT_USER_ID).
    users_table = table(
        "users",
        column("id", sa.Integer),
        column("email", sa.String),
        column("display_name", sa.String),
    )
    op.bulk_insert(
        users_table,
        [{"id": 1, "email": "local@tradeedge.ai", "display_name": "Local Trader"}],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE id = 1")
    op.drop_index('ix_ai_analyses_user_created', table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_trade_created', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index('ix_trades_user_session', table_name='trades')
    op.drop_index('ix_trades_user_pair', table_name='trades')
    op.drop_index('ix_trades_user_date', table_name='trades')
    op.drop_table('trades')
    op.drop_table('scoring_weights')
    op.drop_table('ml_models')
    op.drop_table('ml_exports')
    op.drop_table('users')
    # ### end Alembic commands ###
